services:
  - type: web
    name: securis
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      python -m pip install -e .
    startCommand: gunicorn app.main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
    env: python 