services:
  - type: web
    name: securis
    runtime: python
    buildCommand: |
      mkdir -p logs
      pip install -r requirements.txt
      python -m pip install -e .
    startCommand: gunicorn app.main:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: PORT
        value: 8000
    env: python 