services:
  - type: web
    name: securis
    runtime: python
    buildCommand: |
      mkdir -p logs
      pip install --upgrade pip
      pip install -r requirements.txt
      python -m pip install -e .
    startCommand: gunicorn --bind 0.0.0.0:$PORT app.main:app --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: PORT
        value: $PORT
    env: python
    healthCheckPath: /health
    autoDeploy: true 